"""empty message

Revision ID: 0fb4fa983d60
Revises: 285e5f172c98
Create Date: 2022-01-26 19:13:03.853353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb4fa983d60'
down_revision = '285e5f172c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cards_card_name_key', 'cards', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cards_card_name_key', 'cards', ['card_name'])
    # ### end Alembic commands ###
