"""empty message

Revision ID: 5ea55d8f5494
Revises: d36848662959
Create Date: 2022-01-20 16:24:54.215472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ea55d8f5494'
down_revision = 'd36848662959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'mana_cost',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('cards', 'colors',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('cards', 'color_identity',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('decks', 'updated_at')
    op.drop_column('decks', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('decks', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('cards', 'color_identity',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('cards', 'colors',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('cards', 'mana_cost',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
