"""empty message

Revision ID: d36848662959
Revises: a92062040a48
Create Date: 2022-01-20 14:16:18.308607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36848662959'
down_revision = 'a92062040a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'decks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decks', type_='foreignkey')
    op.drop_column('decks', 'user_id')
    # ### end Alembic commands ###
