"""empty message

Revision ID: d2a1d6b896e1
Revises: e7c20be057ba
Create Date: 2022-01-21 16:14:08.586242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a1d6b896e1'
down_revision = 'e7c20be057ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cards_oracle_text_key', 'cards', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cards_oracle_text_key', 'cards', ['oracle_text'])
    # ### end Alembic commands ###
