"""empty message

Revision ID: 0052b9f7162a
Revises: ff1b74a10279
Create Date: 2022-01-26 17:02:09.604693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0052b9f7162a'
down_revision = 'ff1b74a10279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deck_cards', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('deck_cards', sa.Column('quantity', sa.Integer(), nullable=True))
    op.alter_column('deck_cards', 'card_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('deck_cards', 'deck_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deck_cards', 'deck_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('deck_cards', 'card_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('deck_cards', 'quantity')
    op.drop_column('deck_cards', 'id')
    # ### end Alembic commands ###
