"""empty message

Revision ID: 43541704935d
Revises: 7ff82741f465
Create Date: 2022-02-18 13:11:11.110594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43541704935d'
down_revision = '7ff82741f465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('username', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'username')
    # ### end Alembic commands ###
