"""empty message

Revision ID: 7bc64f0c464d
Revises: b714f8df6452
Create Date: 2022-01-27 10:16:21.061305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc64f0c464d'
down_revision = 'b714f8df6452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('decks_deck_name_key', 'decks', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('decks_deck_name_key', 'decks', ['deck_name'])
    # ### end Alembic commands ###
