"""empty message

Revision ID: b714f8df6452
Revises: 862710766126
Create Date: 2022-01-26 19:26:57.155140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b714f8df6452'
down_revision = '862710766126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cards_card_name_key', 'cards', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cards_card_name_key', 'cards', ['card_name'])
    # ### end Alembic commands ###
