"""empty message

Revision ID: e7c20be057ba
Revises: 20cf5f97257f
Create Date: 2022-01-20 16:27:06.061617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c20be057ba'
down_revision = '20cf5f97257f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cards_mana_cost_key', 'cards', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cards_mana_cost_key', 'cards', ['mana_cost'])
    # ### end Alembic commands ###
